-- Account
INSERT IGNORE INTO account VALUES (1, 0, 'XYZ Pvt Ltd','SELLER',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Tax Rules
INSERT IGNORE INTO tax_rules VALUES(1,0,'1005','SOME ITEMS OF 5 PERCENT',5);
INSERT IGNORE INTO tax_rules VALUES(1,0,'1012','SOME PRODUCTS OF 10 PERCENT',10);