-- Account
INSERT IGNORE INTO account VALUES (1, 0, 'Seller 1','SELLER',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Tax Rules
INSERT IGNORE INTO tax_rules VALUES(1,0,'1005','SOME ITEMS OF 5 PERCENT',5);
INSERT IGNORE INTO tax_rules VALUES(2,0,'1010','SOME PRODUCTS OF 10 PERCENT',10);